package enums;

public enum RegionCards {
	// TODO populate resources
	// RIVENDELL
	BOROMIR, GIMLI, LEGOLAS, ARAGORN, MITHRIL, STING, ARWEN, ELROD, ANDURIL,  
	//MORIA
	BOOK, PIPE,
	//LOTHLORIEN
	STICK, MIROUVOR, LEMBAS, GALADRIEL, KARFITSA, BELT, VIAL, ELESAR, 
	//HELM'S DEEP
	SHADOWFAX,	RIDERS_OF_ROHAN, EOMER, 
	// SHELOB'S LAIR
	GOLOUM, FARAMIR,
	// MORDOR
	EOWIN, ARMY_OF_THE_DEAD, TREEBEARD
}
